version: '3'
services:
  db:
    image: mysql:latest
    container_name: pinkFlamingosContainer
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=superSecretPassword
      - MYSQL_DATABASE=pinkFlamingosDatabase
    volumes:
      - /home/siva/Documents/pinkFlamingos/db:/var/lib/mysql